[package]
name = "bot_cmd_eval"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
anyhow.workspace = true
bot_core.path = "../bot_core"
poise.workspace = true
rlimit.workspace = true
tokio.workspace = true

[lints]
workspace = true
