[package]
name = "bot_cmd_eval"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
bot_core.path = "../bot_core"
eyre.workspace = true
poise.workspace = true
rlimit.workspace = true
tokio.workspace = true

[lints]
workspace = true
