[package]
name = "bot_cmd_role_icon"
version.workspace = true
edition.workspace = true

[lib]
path = "lib.rs"

[dependencies]
bot_core.path = "../bot_core"
emojis.workspace = true
eyre.workspace = true
poise.workspace = true
rand.workspace = true
serde.workspace = true

[lints]
workspace = true
