[package]
name = "bot_cmd_roles"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
bot_core.path = "../bot_core"
eyre.workspace = true
poise.workspace = true
serde.workspace = true
tracing.workspace = true

[lints]
workspace = true

